name: "terrafom-action"
on:
  push:
    branches:
      - master
  
jobs:
    terraform:
      name: "terraform"
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY}}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup terraform
          uses: hashicorp/setup-terraform@v1
        - name: Terraform init
          id: init
          run: terraform init
        - name: Terraform plan
          id: plan
          run: terraform plan
        - name: Terrafom apply
          id: apply
          if: github.event_name == 'push'
          run: terraform destroy --auto-approve
